#pragma once

enum Commands {
    COMMAND_DEV_IDENTIFICATION = 0,

    COMMAND_TRAN_RESET = 10,
    COMMAND_TRAN_TRANSLATE = 11,
    COMMAND_TRAN_ROTATE = 12,
    COMMAND_TRAN_SHEAR = 13,
    COMMAND_TRAN_SKEW = 14,
    COMMAND_TRAN_SCALE = 15,

    COMMAND_FRAME_FREE = 20,
    COMMAND_FRAME_PUSH = 21,

    COMMAND_KEEP_ALIVE = 30
};